### PR TITLE
fixed Makefile to compile on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by specht**
Nice project! One minor linking problem though: the linker complained about an undefined reference to `ortp_init' and many more, although the library is installed and the symbol is in there.

Placing the -l library statements at the end of the gcc commands did the trick for me, so if this still works for you, please consider merging this commit.

### CODE REVIEW

**Comment by carpikes** [comment]
thanks! merged!
